<?php
define('DB_SERVER', 'localhost');
define('DB_SERVER_USERNAME', 'YOUR-USERNAME');
define('DB_SERVER_PASSWORD', 'YOUR-PASSWORD');
define('DB_DATABASE', 'YOUR-DATABASE');

$connexion = new mysqli(DB_SERVER, DB_SERVER_USERNAME, DB_SERVER_PASSWORD, DB_DATABASE);
?>